name: Run Connection Cards Sync

on:
  schedule:
    - cron: "0 19 * * 0" # 1:00 PM CST on Sunday
    - cron: "0 20 * * 0" # 2:00 PM CST on Sunday
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies from requirements.txt
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run Connection Cards Sync script
        env:
          PCO_APP_ID: ${{ secrets.PCO_APP_ID }}
          PCO_SECRET: ${{ secrets.PCO_SECRET }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python CCsubmission_import.py
