name: Run Sermon Upload

on:
  schedule:
    # Runs every Sunday at 2:00 PM CST (20:00 UTC)
    - cron: "0 20 * * 0"
  workflow_dispatch: # allows manual trigger from GitHub Actions tab

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Run Sermon Upload Script
        env:
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
          BOX_CLIENT_ID: ${{ secrets.BOX_CLIENT_ID }}
          BOX_CLIENT_SECRET: ${{ secrets.BOX_CLIENT_SECRET }}
          BOX_ENTERPRISE_ID: ${{ secrets.BOX_ENTERPRISE_ID }}
          BOX_JWT_KEY_ID: ${{ secrets.BOX_JWT_KEY_ID }}
          BOX_JWT_PRIVATE_KEY: ${{ secrets.BOX_JWT_PRIVATE_KEY }}
          BOX_JWT_PASSPHRASE: ${{ secrets.BOX_JWT_PASSPHRASE }}
          VIMEO_ACCESS_TOKEN: ${{ secrets.VIMEO_ACCESS_TOKEN }}
          SPREAKER_CLIENT_ID: ${{ secrets.SPREAKER_CLIENT_ID }}
          SPREAKER_CLIENT_SECRET: ${{ secrets.SPREAKER_CLIENT_SECRET }}
          WEBFLOW_TOKEN: ${{ secrets.WEBFLOW_TOKEN }}
          COLLECTION_ID: ${{ secrets.COLLECTION_ID }}
        run: python upload_sermon.py
