name: Run Sermon Upload

on:
  schedule:
    # Runs every Sunday at 2:00 PM CST (20:00 UTC)
    - cron: "0 20 * * 0"
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Run Sermon Upload Script
        env:
          BOX_JWT_JSON: ${{ secrets.BOX_JWT_JSON }}

          # ✅ Google Service Account JSON for Sheets
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}

          # ✅ Vimeo API token
          VIMEO_ACCESS_TOKEN: ${{ secrets.VIMEO_ACCESS_TOKEN }}

          # ✅ Spreaker API tokens
          SPREAKER_ACCESS_TOKEN: ${{ secrets.SPREAKER_ACCESS_TOKEN }}

          # ✅ Webflow API token and collection ID
          WEBFLOW_TOKEN: ${{ secrets.WEBFLOW_TOKEN }}
          COLLECTION_ID: ${{ secrets.COLLECTION_ID }}
        run: python upload_sermon.py
