name: Sync Events

on:
  workflow_dispatch:   # Manual trigger
  schedule:
    - cron: '0 13 * * *'  # Daily at 8AM CST (13:00 UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          PCO_APP_ID: ${{ secrets.PCO_APP_ID }}
          PCO_SECRET: ${{ secrets.PCO_SECRET }}
          WEBFLOW_TOKEN: ${{ secrets.WEBFLOW_TOKEN }}
          COLLECTION_ID: ${{ secrets.COLLECTION_ID }}
        run: python Event_automation.py
